import style from "../styles/home.module.scss";
//import Head from 'next/head'
//<Head>
//<title>Create Next App</title>
//<meta name="description" content="Generated by create next app" />
//<link rel="icon" href="/favicon.ico" />
//</Head>

export default function Home() {
  return (
    <div>
        <div className={style.hero}>
        Hey Guys,
        <br />I’m Yoni. I’m a <span>Content creator</span> <br />and self taught web developer
        </div>
    </div>
  );
};
